
spring:
  application:
    name: library-management-system
  
  datasource:
    url: jdbc:h2:mem:librarydb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    com.library: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

